version: "3"

vars:
  CHARTS_DIR: charts
  DEFAULT_CHART: mosquitto

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  discover-charts:
    desc: List all available charts
    cmds:
      - find {{.CHARTS_DIR}} -name Chart.yaml -exec dirname {} \; | sed 's|{{.CHARTS_DIR}}/||' | sort
    silent: true

  tools:
    desc: Ensure required tools are installed
    vars:
      HELM_UNITTEST_VERSION:
        sh: grep '^HELM_UNITTEST_VERSION=' .github/versions.env | cut -d= -f2
    cmds:
      - |
        which helm || (echo "Install Helm: https://helm.sh/docs/intro/install/" && exit 1)
      - |
        which ct || echo "Optional: Install chart-testing (ct) for ct lint"
      - |
        which kubeconform || (echo "Install kubeconform: https://github.com/yannh/kubeconform#installation" && exit 1)
      - |
        which helm-docs || echo "Optional: Install helm-docs for README generation"
      - |
        if ! helm plugin list 2>/dev/null | grep -q "unittest"; then
          echo "Installing helm-unittest {{.HELM_UNITTEST_VERSION}}..."
          helm plugin install https://github.com/helm-unittest/helm-unittest --version {{.HELM_UNITTEST_VERSION}}
        fi

  helm-lint:
    desc: "Run helm lint (usage: task helm-lint CHART=mosquitto)"
    cmds:
      - helm lint {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}}

  unittest:
    desc: "Run helm unittest (usage: task unittest CHART=mosquitto)"
    deps: [tools]
    cmds:
      - helm unittest {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}}

  kubeconform:
    desc: "Validate rendered templates (usage: task kubeconform CHART=mosquitto)"
    cmds:
      - |
        helm template test {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}} \
          | kubeconform -strict -ignore-missing-schemas -summary

  verify:
    desc: "Run all checks for a chart (usage: task verify CHART=mosquitto)"
    deps: [tools]
    cmds:
      - task: helm-lint
        vars: { CHART: "{{.CHART | default .DEFAULT_CHART}}" }
      - task: unittest
        vars: { CHART: "{{.CHART | default .DEFAULT_CHART}}" }
      - task: kubeconform
        vars: { CHART: "{{.CHART | default .DEFAULT_CHART}}" }

  verify-all:
    desc: Run all checks for all charts
    deps: [tools]
    cmds:
      - |
        for chart in $(task discover-charts --silent); do
          echo "=== Verifying $chart ==="
          task verify CHART=$chart
        done

  ct-lint:
    desc: "Run chart-testing lint (usage: task ct-lint CHART=mosquitto)"
    cmds:
      - ct lint --charts {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}}

  ct-lint-all:
    desc: Run chart-testing lint on all changed charts
    cmds:
      - ct lint

  template:
    desc: "Render chart templates (usage: task template CHART=mosquitto)"
    cmds:
      - helm template test {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}} --debug

  docs:
    desc: "Generate README for a chart (usage: task docs CHART=mosquitto)"
    cmds:
      - helm-docs --chart-search-root {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}} --sort-values-order file

  docs-all:
    desc: Generate READMEs for all charts
    cmds:
      - helm-docs --sort-values-order file

  package:
    desc: "Package a chart (usage: task package CHART=mosquitto)"
    cmds:
      - helm dependency build {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}}
      - helm package {{.CHARTS_DIR}}/{{.CHART | default .DEFAULT_CHART}} --destination .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf .cr-release-packages *.tgz
      - echo "Cleaned"
