# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

# Secrets for pulling images from private repositories
imagePullSecrets: []

# Override the chart name
nameOverride: ""
fullnameOverride: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  # Service annotations for load balancer configuration
  annotations: {}
    # MetalLB examples:
    # metallb.universe.tf/loadBalancerIPs: "192.168.1.100"
    # metallb.universe.tf/address-pool: "production-public-ips"
    # Traefik examples:
    # traefik.ingress.kubernetes.io/service.loadbalancer.method: "drr"
    # Cloud provider examples:
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: "myResourceGroup"
  # LoadBalancer configuration (for MetalLB, cloud providers, etc.)
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  # External traffic policy for LoadBalancer and NodePort
  externalTrafficPolicy: Cluster
  # Session affinity for service
  sessionAffinity: None
  # MQTT broker ports
  ports:
    mqtt:
      enabled: true
      port: 1883
      targetPort: 1883
      protocol: TCP
      # NodePort for NodePort service type (leave empty for auto-assignment)
      nodePort: ""
    mqttTls:
      enabled: false
      port: 8883
      targetPort: 8883
      protocol: TCP
      # NodePort for NodePort service type (leave empty for auto-assignment)
      nodePort: ""
      # TLS configuration (only used if enabled)
      tls:
        # Secret containing TLS certificates
        secretName: ""
        # Keys in the secret (customize if your secret uses different key names)
        caFile: "ca.crt"      # CA certificate
        certFile: "tls.crt"   # Server certificate
        keyFile: "tls.key"    # Server private key
    websocket:
      enabled: false
      port: 9001
      targetPort: 9001
      protocol: TCP
      # NodePort for NodePort service type (leave empty for auto-assignment)
      nodePort: ""

# Host networking configuration
hostNetwork:
  # Enable host networking (pod uses host's network namespace)
  enabled: false
  # DNS policy when using host networking
  dnsPolicy: ClusterFirstWithHostNet

# Host port configuration (alternative to hostNetwork)
hostPorts:
  # Enable binding to host ports
  enabled: false
  # Host ports configuration
  mqtt:
    # Host port for MQTT (leave empty to disable)
    port: ""
    # Host IP to bind to (empty = all interfaces)
    hostIP: ""
  mqttTls:
    # Host port for MQTT TLS (leave empty to disable)
    port: ""
    # Host IP to bind to (empty = all interfaces)
    hostIP: ""
  websocket:
    # Host port for WebSocket (leave empty to disable)
    port: ""
    # Host IP to bind to (empty = all interfaces)
    hostIP: ""

ingress:
  # Only needed for WebSocket connections (HTTP-based MQTT)
  # Traditional MQTT (TCP) should use LoadBalancer or NodePort service type
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: mosquitto.local
      paths:
        - path: /mqtt
          pathType: Prefix
          service:
            name: websocket  # Only websocket port is HTTP-compatible
  tls: []
  #  - secretName: mosquitto-tls
  #    hosts:
  #      - mosquitto.local

# Resource limits and requests
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Health checks
livenessProbe:
  tcpSocket:
    port: mqtt
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  tcpSocket:
    port: mqtt
  initialDelaySeconds: 5
  periodSeconds: 5


# Mosquitto configuration
config:
  # Allow anonymous connections (automatically disabled if users are defined)
  allowAnonymous: true
  # Log level: error, warning, notice, information, subscribe, unsubscribe, websockets, none, all
  logLevel: information
  # Maximum concurrent client connections (0 = unlimited)
  maxConnections: 0
  # Additional custom configuration
  extraConfig: ""

# Authentication configuration
auth:
  # Users for password-based authentication (stored in ConfigMap)
  # Note: Ignored if auth.secretRef.name is set
  users: []
    # - username: admin
    #   password: admin123        # Plaintext password (development)
    # - username: user1
    #   passwordHash: "$6$..."    # Pre-hashed password (production)

  # Reference to existing secret containing password file
  # If set, this takes precedence over auth.users
  secretRef:
    # Name of the secret containing the password file
    name: ""
    # Key in the secret containing the password file content
    # Defaults to "passwd" if not specified
    key: "passwd"

  # Access Control Lists
  acls: []
    # - user: admin
    #   topic: "#"
    #   access: readwrite
    # - user: user1
    #   topic: "devices/user1/#"
    #   access: readwrite
    # - pattern: "readwrite %u/#"  # %u replaced with username

persistence:
  enabled: false
  # Storage class for PVC
  # Set to "-" to disable dynamic provisioning and use default storage class
  # Set to "" to use cluster default storage class
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # Use an existing PVC instead of creating a new one
  # If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # Annotations for PVC
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
