apiVersion: v2
name: lidarr
description: Music collection manager for usenet and torrent users
type: application
version: "0.1.0"
# renovate: image=linuxserver/lidarr
appVersion: "3.1.0"
icon: https://raw.githubusercontent.com/Lidarr/Lidarr/develop/Logo/Lidarr.svg
keywords:
  - music
  - organizer
  - servarr
home: https://github.com/bdclark/helm-charts/tree/main/charts/lidarr
sources:
  - https://github.com/bdclark/helm-charts/tree/main/charts/lidarr
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/bdclark/helm-charts/tree/main/charts/lidarr
    - name: Lidarr
      url: https://lidarr.audio
    - name: Lidarr GitHub
      url: https://github.com/Lidarr/Lidarr
maintainers:
  - name: bdclark
    email: brian@clark.zone
    url: https://github.com/bdclark
