apiVersion: v2
name: mosquitto
description: Eclipse Mosquitto MQTT broker
type: application
version: 0.1.0
appVersion: 2.0.18
home: https://github.com/bdclark/helm-charts/tree/main/mosquitto
icon: https://raw.githubusercontent.com/eclipse/mosquitto/master/logo/mosquitto-logo-min.svg
keywords:
  - mqtt
  - mosquitto
  - eclipse
  - iot
