suite: test deployment
templates:
  - deployment.yaml
tests:
  - it: should create deployment with default values
    asserts:
      - isKind:
          of: Deployment

  - it: should use app image
    asserts:
      - matchRegex:
          path: spec.template.spec.containers[0].image
          pattern: "^example/app:"
