apiVersion: v2
name: seerr
description: Request management for media libraries
type: application
version: "0.1.0"
# renovate: image=ghcr.io/sct/seerr
appVersion: "3.1.0"
icon: https://raw.githubusercontent.com/seerr-team/seerr/refs/heads/main/public/os_icon.svg
keywords:
  - requests
  - media
  - seerr
  - overseerr
home: https://github.com/bdclark/helm-charts/tree/main/charts/seerr
sources:
  - https://github.com/bdclark/helm-charts/tree/main/charts/seerr
  - https://github.com/seerr-team/seerr
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/bdclark/helm-charts/tree/main/charts/seerr
    - name: Seerr
      url: https://seerr.dev
    - name: Seerr GitHub
      url: https://github.com/seerr-team/seerr
maintainers:
  - name: bdclark
    email: brian@clark.zone
    url: https://github.com/bdclark
