apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    {{- range $name, $config := .Values.service.ports }}
    {{- if $config.enabled }}
    - port: {{ $config.port }}
      targetPort: {{ $config.targetPort }}
      protocol: {{ $config.protocol }}
      name: {{ $name }}
      {{- if and (eq $.Values.service.type "NodePort") $config.nodePort }}
      nodePort: {{ $config.nodePort }}
      {{- end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
