name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main
      - develop
    paths:
      - 'charts/**'

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install yamllint
        run: pip install yamllint

      - name: Add helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Run chart-testing (list)
        id: list
        run: ct list-changed --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        if: steps.list.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0
        with:
          wait: 120s

      - name: Run chart-testing (install)
        if: steps.list.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

